// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Arcesoft.TicTacToe.Evolution.Tests.Integration.Scenarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PersistanceFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "Persistance.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Persistance", "\tVerify persistance functionality", ProgrammingLanguage.CSharp, new string[] {
                        "Integration"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Persistance")))
            {
                global::Arcesoft.TicTacToe.Evolution.Tests.Integration.Scenarios.PersistanceFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line 6
 testRunner.Given("I have a container", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.Given("I have an evolution factory", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.Given("I have a data access", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.Given("I delete all individuals", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.Given("I delete all regions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data access should save population")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Persistance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integration")]
        public virtual void DataAccessShouldSavePopulation()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data access should save population", ((string[])(null)));
#line 12
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "MutationRate",
                        "MaximumPopulationSize",
                        "IndividualChildBearingLimit",
                        "MaximumGenesPerIndividual",
                        "BreederType",
                        "FitnessEvaluatorType",
                        "MatchTournaments"});
            table1.AddRow(new string[] {
                        "0",
                        "2",
                        "5",
                        "2",
                        "ASexual",
                        "AllOrNothing",
                        "1"});
#line 13
 testRunner.Given("I have the following population settings", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Generation"});
            table2.AddRow(new string[] {
                        "99000000-0000-0000-0000-000000000000",
                        "Giggidy",
                        "5500"});
#line 16
 testRunner.Given("I have the following population", ((string)(null)), table2, "Given ");
#line 19
 testRunner.Given("I clear all individuals from my population", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Turn",
                        "Priority",
                        "Alleles"});
            table3.AddRow(new string[] {
                        "First",
                        "3",
                        "____R____"});
            table3.AddRow(new string[] {
                        "Ninth",
                        "34",
                        "DDDDDDDDR"});
#line 20
 testRunner.Given("I add an individual called \'Alpha\' with id \'10000000-0000-0000-0000-000000000000\'" +
                    " and with the following genes to my population", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Turn",
                        "Priority",
                        "Alleles"});
            table4.AddRow(new string[] {
                        "Second",
                        "22",
                        "__R__X___"});
            table4.AddRow(new string[] {
                        "Third",
                        "4",
                        "DDD__DDDR"});
#line 24
 testRunner.Given("I add an individual called \'Beta\' with id \'20000000-0000-0000-0000-000000000000\' " +
                    "and with the following genes to my population", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Turn",
                        "Priority",
                        "Alleles"});
            table5.AddRow(new string[] {
                        "Fourth",
                        "1",
                        "XO__R____"});
            table5.AddRow(new string[] {
                        "Eigth",
                        "20",
                        "__DDDDDDR"});
#line 28
 testRunner.Given("I add an individual called \'Gamma\' with id \'30000000-0000-0000-0000-000000000000\'" +
                    " and with the following genes to my population", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Turn",
                        "Priority",
                        "Alleles"});
            table6.AddRow(new string[] {
                        "Fourth",
                        "9",
                        "XO__R____"});
            table6.AddRow(new string[] {
                        "Eigth",
                        "20",
                        "__DDDDDDR"});
#line 32
 testRunner.Given("I add an individual called \'Cappa\' with id \'40000000-0000-0000-0000-000000000000\'" +
                    " and with the following genes to my population", ((string)(null)), table6, "Given ");
#line 36
 testRunner.When("I save my population", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Generation"});
            table7.AddRow(new string[] {
                        "99000000-0000-0000-0000-000000000000",
                        "Giggidy",
                        "5500"});
#line 37
 testRunner.Then("I expect the saved population to contain", ((string)(null)), table7, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "MutationRate",
                        "MaximumPopulationSize",
                        "IndividualChildBearingLimit",
                        "MaximumGenesPerIndividual",
                        "BreederType",
                        "FitnessEvaluatorType",
                        "MatchTournaments"});
            table8.AddRow(new string[] {
                        "0",
                        "2",
                        "5",
                        "2",
                        "ASexual",
                        "AllOrNothing",
                        "1"});
#line 40
 testRunner.Then("I expect the saved population to contain the following evolution settings", ((string)(null)), table8, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Turn",
                        "Priority",
                        "Alleles"});
            table9.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Alpha",
                        "First",
                        "3",
                        "____R____"});
            table9.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Alpha",
                        "Ninth",
                        "34",
                        "DDDDDDDDR"});
            table9.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Beta",
                        "Second",
                        "22",
                        "__R__X___"});
            table9.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Beta",
                        "Third",
                        "4",
                        "DDD__DDDR"});
            table9.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "Gamma",
                        "Fourth",
                        "1",
                        "XO__R____"});
            table9.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "Gamma",
                        "Eigth",
                        "20",
                        "__DDDDDDR"});
            table9.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Cappa",
                        "Fourth",
                        "9",
                        "XO__R____"});
            table9.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Cappa",
                        "Eigth",
                        "20",
                        "__DDDDDDR"});
#line 43
 testRunner.Then("I expect the saved population to contain the following individuals", ((string)(null)), table9, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data access should find populations")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Persistance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integration")]
        public virtual void DataAccessShouldFindPopulations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data access should find populations", ((string[])(null)));
#line 54
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "MutationRate",
                        "MaximumPopulationSize",
                        "IndividualChildBearingLimit",
                        "MaximumGenesPerIndividual",
                        "BreederType",
                        "FitnessEvaluatorType",
                        "MatchTournaments"});
            table10.AddRow(new string[] {
                        "0",
                        "2",
                        "5",
                        "2",
                        "ASexual",
                        "AllOrNothing",
                        "1"});
#line 55
 testRunner.Given("I have the following population settings", ((string)(null)), table10, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table11.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy"});
            table11.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Giggid"});
            table11.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird"});
            table11.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Coolio"});
#line 58
 testRunner.Given("I have the following populations", ((string)(null)), table11, "Given ");
#line 64
 testRunner.Given("I save my populations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 65
 testRunner.When("I find populations by name \'gIGgIDY\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table12.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy"});
            table12.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird"});
#line 66
 testRunner.Then("I expect the find populations search results to only contain", ((string)(null)), table12, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data access should save region")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Persistance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integration")]
        public virtual void DataAccessShouldSaveRegion()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data access should save region", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "MutationRate",
                        "MaximumPopulationSize",
                        "IndividualChildBearingLimit",
                        "MaximumGenesPerIndividual",
                        "BreederType",
                        "FitnessEvaluatorType",
                        "MatchTournaments"});
            table13.AddRow(new string[] {
                        "0",
                        "2",
                        "5",
                        "2",
                        "ASexual",
                        "AllOrNothing",
                        "1"});
#line 72
 testRunner.Given("I have the following population settings", ((string)(null)), table13, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Generation"});
            table14.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Alpha",
                        "1500"});
            table14.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Beta",
                        "110"});
            table14.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "Cappa",
                        "70"});
#line 75
 testRunner.Given("I have the following populations", ((string)(null)), table14, "Given ");
#line 80
 testRunner.Given("I evolve the populations \'1\' times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 81
 testRunner.Given("I save my populations", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "InternalMigrationEnabled",
                        "ExternalMigrationEnabled"});
            table15.AddRow(new string[] {
                        "true",
                        "true"});
#line 82
 testRunner.Given("I have the following region settings", ((string)(null)), table15, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "DateCreated",
                        "Age"});
            table16.AddRow(new string[] {
                        "880000000-0000-0000-0000-00000000000",
                        "Bob",
                        "10/18/1978",
                        "33"});
            table16.AddRow(new string[] {
                        "990000000-0000-0000-0000-00000000000",
                        "Sally",
                        "9/14/2012",
                        "8"});
#line 85
 testRunner.Given("I have the following regions", ((string)(null)), table16, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table17.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000"});
            table17.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000"});
#line 89
 testRunner.Given("I add the following given populations to region \'880000000-0000-0000-0000-0000000" +
                    "0000\'", ((string)(null)), table17, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table18.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000"});
#line 93
 testRunner.Given("I add the following given populations to region \'990000000-0000-0000-0000-0000000" +
                    "0000\'", ((string)(null)), table18, "Given ");
#line 96
 testRunner.When("I save my regions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "DateCreated",
                        "Age"});
            table19.AddRow(new string[] {
                        "880000000-0000-0000-0000-00000000000",
                        "Bob",
                        "10/18/1978 7:00:00 AM +00:00",
                        "33"});
#line 97
 testRunner.Then("I expect the saved region \'880000000-0000-0000-0000-00000000000\' to contain", ((string)(null)), table19, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table20.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000"});
            table20.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000"});
#line 100
 testRunner.Then("I expect the saved region \'880000000-0000-0000-0000-00000000000\' to contain the f" +
                    "ollowing populations", ((string)(null)), table20, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "DateCreated",
                        "Age"});
            table21.AddRow(new string[] {
                        "99000000-0000-0000-0000-00000000000",
                        "Sally",
                        "9/14/2012 7:00:00 AM +00:00",
                        "8"});
#line 104
 testRunner.Then("I expect the saved region \'990000000-0000-0000-0000-00000000000\' to contain", ((string)(null)), table21, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id"});
            table22.AddRow(new string[] {
                        "30000000-0000-0000-0000-00000000000"});
#line 107
 testRunner.Then("I expect the saved region \'990000000-0000-0000-0000-00000000000\' to contain the f" +
                    "ollowing populations", ((string)(null)), table22, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data access should search regions by name")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Persistance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integration")]
        public virtual void DataAccessShouldSearchRegionsByName()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data access should search regions by name", ((string[])(null)));
#line 111
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "DateCreated"});
            table23.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy",
                        "10/18/1978 7:00:00 AM +00:00"});
            table23.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Giggid",
                        "10/19/1978 7:00:00 AM +00:00"});
            table23.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird",
                        "10/20/1978 7:00:00 AM +00:00"});
            table23.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Coolio",
                        "10/21/1978 7:00:00 AM +00:00"});
#line 112
 testRunner.Given("I have the following regions", ((string)(null)), table23, "Given ");
#line 118
 testRunner.Given("I save my regions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 119
 testRunner.When("I find regions by name \'gIGgIDY\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "DateCreated"});
            table24.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy",
                        "10/18/1978 7:00:00 AM +00:00"});
            table24.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird",
                        "10/20/1978 7:00:00 AM +00:00"});
#line 120
 testRunner.Then("I expect the search regions to only contain", ((string)(null)), table24, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Data access should search regions most recent")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Persistance")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Integration")]
        public virtual void DataAccessShouldSearchRegionsMostRecent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Data access should search regions most recent", ((string[])(null)));
#line 125
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table25.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy"});
            table25.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Giggid"});
            table25.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird"});
            table25.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Coolio"});
#line 126
 testRunner.Given("I have the following regions", ((string)(null)), table25, "Given ");
#line 132
 testRunner.Given("I save my regions", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 133
 testRunner.When("I find regions by most recent \'10\' days with a limit of \'10\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name"});
            table26.AddRow(new string[] {
                        "10000000-0000-0000-0000-000000000000",
                        "Giggidy"});
            table26.AddRow(new string[] {
                        "20000000-0000-0000-0000-000000000000",
                        "Giggid"});
            table26.AddRow(new string[] {
                        "30000000-0000-0000-0000-000000000000",
                        "QuagmadiusGiggidyTheThird"});
            table26.AddRow(new string[] {
                        "40000000-0000-0000-0000-000000000000",
                        "Coolio"});
#line 134
 testRunner.Then("I expect the search regions to only contain", ((string)(null)), table26, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
